version: '2'
services:
  haproxy-whiteboard:
    image: haproxy-whiteboard
    build: whiteboard/.
    container_name: 'haproxy-whiteboard'
    hostname: 'haproxy-whiteboard'
    volumes:
      - '${current_dir}/whiteboard:/app'
    ports:
      - '5000:5000'

  haproxy-proxy:
    image: haproxy-proxy
    build: haproxy/.
    container_name: 'haproxy-proxy'
    hostname: 'haproxy-proxy'
    #volumes:
    #  - '${current_dir}/whiteboard:/app'
    #ports:
    #  - '5000:5000'
    #command: haproxy -S 0.0.0.0:1234 -W -db -f /usr/local/etc/haproxy/haproxy.cfg
